'use client'; 

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation'; 
import Link from 'next/link';
import { CheckCircleIcon } from '@heroicons/react/24/solid';

export default function LandingPage() {
  const [isLoading, setIsLoading] = useState(true); 
  const router = useRouter();

  useEffect(() => {
    // Check for a token in the browser's storage
    const token = localStorage.getItem('token');
    
    if (token) {
      // If token exists, redirect to the dashboard
      router.push('/dashboard');
    } else {
      // If no token, stop loading and show the landing page
      setIsLoading(false);
    }
  }, [router]); // Run this check once on page load
  

  const features = [
    {
      name: 'AI-Powered Insights',
      description: 'Get smart, practical tips to save money, generated by AI that understands your student budget.',
    },
    {
      name: 'Scan Receipts Instantly',
      description: 'Use your phone\'s camera to scan receipts, and let our app auto-fill the details. No more manual typing!',
    },
    {
      name: 'Visual Category Tracking',
      description: 'See exactly where your money goes with a simple, colorful chart. Identify spending leaks in seconds.',
    },
    {
      name: 'Mobile-Friendly Design',
      description: 'Track your expenses on the go. Our app is designed to work perfectly on your phone.',
    },
  ];


  if (isLoading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-gray-100">
        <p className="text-lg text-gray-600">Loading...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      <header className="absolute inset-x-0 top-0 z-50">
        <nav className="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
          <div className="flex lg:flex-1">
            <Link href="/" className="-m-1.5 p-1.5">
              <span className="text-2xl font-bold text-blue-600">CashMate</span>
            </Link>
          </div>
          <div className="lg:flex lg:flex-1 lg:justify-end">
            <Link 
              href="/login" 
              className="text-sm font-semibold leading-6 text-gray-900 hover:text-gray-700"
            >
              Log in <span aria-hidden="true">&rarr;</span>
            </Link>
          </div>
        </nav>
      </header>

      <div className="relative isolate px-6 pt-14 lg:px-8">
        <div
          className="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80"
          aria-hidden="true"
        >
          <div
            className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#80ff8c] to-[#0070f3] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
            style={{
              clipPath:
                'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)',
            }}
          />
        </div>

        <div className="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
          <div className="text-center">
            <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
              Finally, a <span className="text-blue-600">smart</span> expense tracker for students.
            </h1>
            <p className="mt-6 text-lg leading-8 text-gray-600">
              Stop guessing where your pocket money went. CashMate uses AI to scan your receipts, find your spending leaks, and give you a simple plan to save.
            </p>
            <div className="mt-10 flex items-center justify-center gap-x-6">
              <Link
                href="/register"
                className="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500  focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Get Started for Free
              </Link>
              <Link 
                href="/login" 
                className="text-sm font-semibold leading-6 text-gray-900"
              >
                Log in <span aria-hidden="true">&rarr;</span>
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="bg-gray-50 py-24 sm:py-32">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-2xl lg:text-center">
            <p className="text-base font-semibold leading-7 text-indigo-600">How It Works</p>
            <h2 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
              Everything you need to manage your money
            </h2>
          </div>
          <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-4xl">
            <dl className="grid max-w-xl grid-cols-1 gap-x-8 gap-y-10 lg:max-w-none lg:grid-cols-2 lg:gap-y-16">
              {features.map((feature) => (
                <div key={feature.name} className="relative pl-16">
                  <dt className="text-base font-semibold leading-7 text-gray-900">
                    <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-600">
                      <CheckCircleIcon className="h-6 w-6 text-white" aria-hidden="true" />
                    </div>
                    {feature.name}
                  </dt>
                  <dd className="mt-2 text-base leading-7 text-gray-600">{feature.description}</dd>
                </div>
              ))}
            </dl>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-white py-10">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <p className="text-center text-xs leading-5 text-gray-500">
                &copy; 2025 CashMate. A project for students.
            </p>
        </div>
      </footer>
    </div>
  );
}

